export const release1EntrySourcePaths = {
  doLogin: "extracted/projectorrays/release1_roseau_dcr0910/habbo_entry/casts/Internal/MovieScript 4 - Entry Movie Scripts.ls",
  loginOk: "extracted/projectorrays/release1_roseau_dcr0910/habbo_entry/casts/Internal/BehaviorScript 159 - loginOk_btn.ls",
  goToRegister: "extracted/projectorrays/release1_roseau_dcr0910/GoldFish/casts/External/BehaviorScript 43 - Go To Regist.ls",
  forgottenPassword: "extracted/projectorrays/release1_roseau_dcr0910/habbo_entry/casts/Internal/BehaviorScript 160 - Forgotten_your_password.ls",
  epConnectionWait: "extracted/projectorrays/release1_roseau_dcr0910/MessengerScript/casts/External/BehaviorScript 9 - EPConnectionWait.ls",
  epConnectionScripts: "extracted/projectorrays/release1_roseau_dcr0910/MessengerScript/casts/External/MovieScript 1 - EnterpriseServer Connection Scripts.ls",
  initUnitInfoListening: "extracted/projectorrays/release1_roseau_dcr0910/GoldFish/casts/External/BehaviorScript 8 - Init Unit Info Listening.ls",
  openNavigator: "extracted/projectorrays/release1_roseau_dcr0910/navigation/casts/External/MovieScript 119 - Navigator Open.ls",
  openMessenger: "extracted/projectorrays/release1_roseau_dcr0910/GoldFish/casts/External/MovieScript 36 - Messenger Open.ls",
  purseOrHelp: "extracted/projectorrays/release1_roseau_dcr0910/navigation/casts/External/MovieScript 292 - Purse Or Help Open.ls",
  changeReg: "extracted/projectorrays/release1_roseau_dcr0910/habbo_entry/casts/Internal/BehaviorScript 141 - change reg.ls",
  waitMyFigureData: "extracted/projectorrays/release1_roseau_dcr0910/habbo_entry/casts/Internal/BehaviorScript 239 - Wait MyFigureData.ls",
  setUserAvatarParts: "extracted/projectorrays/release1_roseau_dcr0910/habbo_entry/casts/Internal/BehaviorScript 241 - Set User Avatar Parts.ls",
  initWelcomeText: "extracted/projectorrays/release1_roseau_dcr0910/habbo_entry/casts/Internal/BehaviorScript 7 - Init Welcome text.ls",
  welcomeWave: "extracted/projectorrays/release1_roseau_dcr0910/habbo_entry/casts/Internal/BehaviorScript 243 - Smily face and waving hand.ls",
  gotoHotel: "extracted/projectorrays/release1_roseau_dcr0910/MessengerScript/casts/External/BehaviorScript 29.ls",
  openNavigatorLoop: "extracted/projectorrays/release1_roseau_dcr0910/habbo_entry/casts/Internal/BehaviorScript 43 - OPENnavigator.ls",
  hotelLoop: "extracted/projectorrays/release1_roseau_dcr0910/GoldFish/casts/External/BehaviorScript 6 - hotel loop.ls",
  nameField: "extracted/projectorrays/release1_roseau_dcr0910/MemberScript/casts/External/BehaviorScript 23 - namefield.ls",
  passwordField: "extracted/projectorrays/release1_roseau_dcr0910/MemberScript/casts/External/BehaviorScript 30 - password field.ls",
  fuseMain: "extracted/projectorrays/release1_roseau_dcr0910/FuseScript/casts/External/MovieScript 1 - Main Script.ls",
  alertHandler: "extracted/projectorrays/release1_roseau_dcr0910/FuseScript/casts/External/MovieScript 4 - Alert_Handler.ls",
  alertParent: "extracted/projectorrays/release1_roseau_dcr0910/FuseScript/casts/External/ParentScript 11 - AlertParent.ls"
} as const;
