export interface HabboBridgePacketNameRegistry {
  readonly serverPacketsByHeader: Readonly<Record<string, string>>;
  readonly clientPacketsByHeader: Readonly<Record<string, string>>;
  readonly serverPacketsByHeaderId?: Readonly<Record<number, string>>;
  readonly clientPacketsByHeaderId?: Readonly<Record<number, string>>;
  readonly framing?: "base64-vl64-terminator" | "v1-text-hash";
  readonly source: string;
}

const release7ServerPacketsByHeader: Readonly<Record<string, string>> = {
  "@@": "HELLO",
  "@A": "SECRETKEY",
  "@B": "RIGHTS",
  "@C": "LOGINOK",
  "@E": "USEROBJ",
  "@F": "PURSE",
  "@G": "SCR_SINFO",
  "@H": "AVAILABLESETS",
  "@L": "BUDDYLIST",
  "@M": "MYPERSISTENTMSG",
  "@P": "FLAT_RESULTS",
  "@O": "MESSENGERREADY",
  "@Q": "BUDDYLIST_UPDATE",
  "@R": "CLC",
  "@S": "OPC_OK",
  "@V": "SCR_NOSUB",
  "@W": "SCR_SOK",
  "@X": "CHAT",
  "@Y": "WHISPER",
  "@Z": "SHOUT",
  "@w": "SEARCH_FLAT_RESULTS",
  "@}": "FAVORITE_FLAT_RESULTS",
  "@\\": "USERS",
  "@^": "OBJECTS",
  "@_": "HEIGHTMAP",
  "@`": "ACTIVE_OBJECTS",
  "@a": "ERROR",
  "@b": "STATUS",
  "@c": "USERBANNED",
  "@d": "NAMEAPPROVED",
  "@e": "NAMEUNACCEPTABLE",
  "@i": "FLAT_LETIN",
  "@j": "YOUARECONTROLLER",
  "@k": "YOUARENOTCONTROLLER",
  "@m": "ITEMS",
  "@n": "FLATPROPERTY",
  "AT": "REMOVEITEM",
  "AX": "STUFFDATAUPDATE",
  "AY": "DOOR_OUT",
  "A\\": "DOOR_IN",
  "A^": "ACTIVEOBJECT_REMOVE",
  "A_": "ACTIVEOBJECT_UPDATE",
  "A~": "CATALOGINDEX",
  "A\x7f": "CATALOGPAGE",
  "AA": "PURCHASE_ERROR",
  "AC": "PURCHASE_OK",
  "AD": "PURCHASE_NOBALANCE",
  "BL": "STRIPINFO",
  "Ac": "REMOVESTRIPITEM",
  "Ae": "STRIPUPDATED",
  "@v": "FLATINFO",
  "@y": "NOFLATSFORUSER",
  "@z": "NOFLATS",
  "@{": "FLATCREATED",
  "@~": "DOORFLAT",
  "@\x7f": "DOORDELETED",
  "@s": "REGISTRATIONOK",
  "AE": "ROOM_READY",
  "AF": "YOUAREMOD",
  "B]": "AVAILABLEBADGES",
  "BD": "BUDDYADDREQUESTS",
  "BE": "CAMPAIGN_MSG",
  "BF": "MESSENGER_MSG",
  "BJ": "REMOVE_BUDDY",
  "BK": "SYSTEMBROADCAST",
  "BS": "NOSUCHUSER",
  "BT": "CRYFORHELP",
  "BU": "PICKED_CRY",
  "B@": "MEMBERINFO",
  "Ba": "MODALERT",
  "Bc": "DATE",
  "Bh": "NAMETOOLONG",
  "CQ": "USERCREDITLOG",
  "CT": "VOUCHER_REDEEM_OK",
  "CU": "VOUCHER_REDEEM_ERROR",
  "C\\": "NAVNODEINFO",
  "C]": "USERFLATCATS",
  "C^": "FLATCAT",
  "C_": "SPACENODEUSERS",
  "C`": "CANTCONNECT",
  "Cd": "USERBADGE",
  "Ce": "AVAILABLEBADGES"
};

const release7ClientPacketsByHeader: Readonly<Record<string, string>> = {
  "@B": "ROOM_DIRECTORY",
  "@D": "TRY_LOGIN",
  "@E": "CHK_VERSION",
  "@F": "SET_UID",
  "@G": "GET_INFO",
  "@H": "GET_CREDITS",
  "@L": "MESSENGER_INIT",
  "@M": "SBUSYF",
  "@O": "MESSENGER_SENDUPDATE",
  "@P": "SUSERF",
  "@Q": "SRCHF",
  "@R": "GETFVRF",
  "@S": "ADD_FAVORITE_ROOM",
  "@T": "DEL_FAVORITE_ROOM",
  "@U": "GETFLATINFO",
  "@W": "DELETEFLAT",
  "@X": "UPDATEFLAT",
  "@Y": "SETFLATINFO",
  "@Z": "SCR_GINFO",
  "@\\": "GETDOORFLAT",
  "@]": "CREATEFLAT",
  "@^": "MESSENGER_C_CLICK",
  "@_": "MESSENGER_C_READ",
  "@`": "MESSENGER_MARKREAD",
  "@a": "MESSENGER_SENDMSG",
  "@b": "MESSENGER_SENDEMAILMSG",
  "@d": "MESSENGER_ASSIGNPERSMSG",
  "@e": "MESSENGER_ACCEPTBUDDY",
  "@f": "MESSENGER_DECLINEBUDDY",
  "@g": "MESSENGER_REQUESTBUDDY",
  "@h": "MESSENGER_REMOVEBUDDY",
  "@i": "FINDUSER",
  "@j": "APPROVENAME",
  "@k": "REGISTER",
  "@r": "SCR_SUBSCRIBE",
  "@s": "SCR_EXTSCR",
  "@v": "GOVIADOOR",
  "@p": "PICK_CRYFORHELP",
  "@y": "TRYFLAT",
  "@{": "GOTOFLAT",
  "@|": "G_HMAP",
  "@}": "G_USRS",
  "@~": "G_OBJS",
  "@\x7f": "G_ITEMS",
  "A@": "G_STAT",
  "AA": "GETSTRIP",
  "AB": "FLATPROPBYITEM",
  "AC": "ADDSTRIPITEM",
  "Ad": "PURCHASE_FROM_CATALOG",
  "Ae": "GET_CATALOG_INDEX",
  "Af": "GET_CATALOG_PAGE",
  "AI": "MOVESTUFF",
  "AJ": "SETSTUFFDATA",
  "AU": "REMOVEITEM",
  "AK": "MOVE",
  "AO": "LOOKTO",
  "AQ": "INTODOOR",
  "AR": "DOORGOIN",
  "AV": "CRYFORHELP",
  "AX": "STOP",
  "AY": "USEITEM",
  "AZ": "PLACESTUFF",
  "A]": "DANCE",
  "A^": "WAVE",
  "Ac": "REMOVESTUFF",
  "A~": "GETROOMAD",
  "A\x7f": "GETUSERCREDITLOG",
  "BA": "REDEEM_VOUCHER",
  "BV": "NAVIGATE",
  "BW": "GETUSERFLATCATS",
  "BX": "GETFLATCAT",
  "BY": "SETFLATCAT",
  "BZ": "GETSPACENODEUSERS",
  "B[": "REMOVEALLRIGHTS",
  "B\\": "GETPARENTCHAIN",
  "B]": "GETAVAILABLEBADGES",
  "B^": "SETBADGE"
};

const release14ServerPacketsByHeaderId: Readonly<Record<number, string>> = {
  0: "HELLO",
  2: "RIGHTS",
  3: "LOGINOK",
  5: "USEROBJ",
  6: "PURSE",
  8: "AVAILABLE_SETS",
  16: "FLAT_RESULTS",
  18: "CLC",
  19: "OPC_OK",
  24: "CHAT",
  25: "WHISPER",
  26: "SHOUT",
  28: "USERS",
  29: "LOGOUT",
  30: "OBJECTS",
  31: "HEIGHTMAP",
  32: "ACTIVE_OBJECTS",
  33: "ERROR",
  34: "STATUS",
  35: "USERBANNED",
  41: "FLAT_LETIN",
  42: "YOUARECONTROLLER",
  43: "YOUARENOTCONTROLLER",
  45: "ITEMS",
  46: "FLATPROPERTY",
  47: "YOUAREMOD",
  50: "PING",
  52: "EPS_NOTIFY",
  54: "FLATINFO",
  55: "SEARCH_FLAT_RESULTS",
  57: "NOFLATSFORUSER",
  58: "NOFLATS",
  61: "FAVORITE_FLAT_RESULTS",
  62: "DOORFLAT",
  63: "DOORDELETED",
  64: "DOORDELETED",
  67: "PURCHASE_OK",
  68: "PURCHASE_NOBALANCE",
  69: "ROOM_READY",
  70: "YOUAREMOD",
  130: "FLATPASSWORD_OK",
  83: "ITEMS",
  84: "REMOVEITEM",
  85: "UPDATEITEM",
  88: "STUFFDATAUPDATE",
  89: "DOOR_OUT",
  91: "DOORBELL_RINGING",
  92: "DOOR_IN",
  93: "ACTIVEOBJECT_ADD",
  94: "ACTIVEOBJECT_REMOVE",
  95: "ACTIVEOBJECT_UPDATE",
  98: "STRIPINFO",
  99: "REMOVESTRIPITEM",
  101: "STRIPUPDATED",
  102: "YOUARENOTALLOWED",
  126: "CATALOGINDEX",
  127: "CATALOGPAGE",
  103: "OTHERNOTALLOWED",
  139: "SYSTEMBROADCAST",
  140: "STRIPINFO",
  141: "CHECKSUM",
  161: "MODALERT",
  166: "ROOM_URL",
  208: "ROOMAD",
  219: "HEIGHTMAP_UPDATE",
  220: "NAVNODEINFO",
  221: "USERFLATCATS",
  222: "FLATCAT",
  223: "SPACENODEUSERS",
  224: "CANTCONNECT",
  225: "SUCCESS",
  226: "FAILURE",
  227: "PARENTCHAIN",
  229: "AVAILABLEBADGES",
  257: "SESSION_PARAMETERS",
  277: "CRYPTO_PARAMETERS",
  278: "END_CRYPTO",
  286: "ROOMFORWARD",
  287: "HOTEL_LOGOUT",
  308: "SOUND_SETTING",
  345: "UPDATE_VOTES",
  361: "TYPING_STATUS",
  370: "ROOMEEVENT_INFO"
};

const release14ClientPacketsByHeaderId: Readonly<Record<number, string>> = {
  4: "TRY_LOGIN",
  5: "VERSIONCHECK",
  6: "UNIQUEID",
  7: "GET_INFO",
  8: "GET_CREDITS",
  2: "ROOM_DIRECTORY",
  13: "SBUSYF",
  16: "SUSERF",
  17: "SRCHF",
  18: "GETFVRF",
  19: "ADD_FAVORITE_ROOM",
  20: "DEL_FAVORITE_ROOM",
  21: "GETFLATINFO",
  23: "DELETEFLAT",
  24: "UPDATEFLAT",
  25: "SETFLATINFO",
  29: "CREATEFLAT",
  47: "GET_PASSWORD",
  52: "CHAT",
  53: "QUIT",
  54: "GOVIADOOR",
  55: "SHOUT",
  56: "WHISPER",
  57: "TRYFLAT",
  58: "LANGCHECK",
  59: "GOTOFLAT",
  60: "G_HMAP",
  61: "G_USRS",
  62: "G_OBJS",
  63: "G_ITEMS",
  64: "G_STAT",
  65: "GETSTRIP",
  66: "FLATPROPBYITEM",
  67: "ADDSTRIPITEM",
  73: "MOVESTUFF",
  74: "SETSTUFFDATA",
  75: "MOVE",
  79: "LOOKTO",
  81: "INTODOOR",
  82: "DOORGOIN",
  85: "REMOVEITEM",
  88: "STOP",
  89: "USEITEM",
  90: "PLACESTUFF",
  93: "DANCE",
  94: "WAVE",
  99: "REMOVESTUFF",
  100: "PURCHASE_FROM_CATALOG",
  101: "GET_CATALOG_INDEX",
  102: "GET_CATALOG_PAGE",
  105: "BTCKS",
  126: "GETROOMAD",
  150: "NAVIGATE",
  151: "GETUSERFLATCATS",
  152: "GETFLATCAT",
  153: "SETFLATCAT",
  154: "GETSPACENODEUSERS",
  155: "REMOVEALLRIGHTS",
  156: "GETPARENTCHAIN",
  157: "GETAVAILABLEBADGES",
  158: "SETBADGE",
  181: "GET_SESSION_PARAMETERS",
  182: "GETINTERST",
  196: "PONG",
  202: "GENERATEKEY",
  204: "SSO",
  206: "INIT_CRYPTO",
  207: "SECRETKEY",
  228: "GET_SOUND_SETTING",
  229: "SET_SOUND_SETTING"
};

const release7BridgeRegistry: HabboBridgePacketNameRegistry = {
  serverPacketsByHeader: release7ServerPacketsByHeader,
  clientPacketsByHeader: release7ClientPacketsByHeader,
  source: "release7_20050729_2 Connection/Multiuser scripts and Auratus v7 packet table"
};

const release14BridgeRegistry: HabboBridgePacketNameRegistry = {
  serverPacketsByHeader: {},
  clientPacketsByHeader: {},
  serverPacketsByHeaderId: release14ServerPacketsByHeaderId,
  clientPacketsByHeaderId: release14ClientPacketsByHeaderId,
  source: "release14.1_b8 hh_entry Login Handler Class regMsgList and Kepler MessageHandler/outgoing composers"
};

const release1ServerPacketsByHeader: Readonly<Record<string, string>> = {
  HELLO: "HELLO",
  ENCRYPTION_OFF: "ENCRYPTION_OFF",
  ENCRYPTION_ON: "ENCRYPTION_ON",
  SECRET_KEY: "SECRET_KEY",
  ERROR: "ERROR",
  USEROBJECT: "USEROBJ",
  WALLETBALANCE: "WALLETBALANCE",
  PH_TICKETS: "PH_TICKETS",
  MESSENGERREADY: "MESSENGERREADY",
  MESSENGERSREADY: "MESSENGERSREADY",
  MESSENGERSMSACCOUNT: "MESSENGERSMSACCOUNT",
  MYPERSISTENTMSG: "MYPERSISTENTMSG",
  BUDDYLIST: "BUDDYLIST",
  BUDDYADDREQUESTS: "BUDDYADDREQUESTS",
  MESSENGER_MSG: "MESSENGER_MSG",
  ALLUNITS: "ALLUNITS",
  UNITMEMBERS: "UNITMEMBERS",
  BUSY_FLAT_RESULTS: "FLAT_RESULTS",
  FLATCREATED: "FLATCREATED",
  FLAT_LETIN: "FLAT_LETIN",
  ROOM_READY: "ROOM_READY",
  HEIGHTMAP: "HEIGHTMAP",
  USERS: "USERS",
  OBJECTS_WORLD: "OBJECTS",
  ACTIVE_OBJECTS: "ACTIVE_OBJECTS",
  ACTIVEOBJECT_ADD: "ACTIVEOBJECT_ADD",
  ACTIVEOBJECT_UPDATE: "ACTIVEOBJECT_UPDATE",
  ACTIVEOBJECT_REMOVE: "ACTIVEOBJECT_REMOVE",
  STUFFDATAUPDATE: "STUFFDATAUPDATE",
  ITEMS: "ITEMS",
  ADDITEM: "ADDITEM",
  UPDATEITEM: "UPDATEITEM",
  REMOVEITEM: "REMOVEITEM",
  YOUAREOWNER: "YOUAREOWNER",
  YOUARECONTROLLER: "YOUARECONTROLLER",
  YOUARENOTCONTROLLER: "YOUARENOTCONTROLLER",
  STATUS: "STATUS",
  CHAT: "CHAT",
  SHOUT: "SHOUT",
  WHISPER: "WHISPER",
  SYSTEMBROADCAST: "SYSTEMBROADCAST",
  SHOWPROGRAM: "SHOWPROGRAM",
  STRIPINFO: "STRIPINFO",
  ORDERINFO: "ORDERINFO",
  ADDSTRIPITEM: "ADDSTRIPITEM",
  PURCHASE_OK: "PURCHASE_OK",
  PURCHASE_NOBALANCE: "PURCHASE_NOBALANCE",
  PURCHASE_ERROR: "PURCHASE_ERROR",
  PURCHASEOK: "PURCHASE_OK",
  PURCHASE_ADDSTRIPITEM: "PURCHASE_ADDSTRIPITEM"
};

const release1ClientPacketsByHeader: Readonly<Record<string, string>> = {
  VERSIONCHECK: "VERSIONCHECK",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  INFORETRIEVE: "INFORETRIEVE",
  MESSENGERINIT: "MESSENGERINIT",
  UNIQUEMACHINEID: "UNIQUEMACHINEID",
  GETCREDITS: "GETCREDITS",
  FINDUSER: "FINDUSER",
  APPROVENAME: "APPROVENAME",
  INITUNITLISTENER: "INITUNITLISTENER",
  GETUNITUSERS: "GETUNITUSERS",
  SEARCHBUSYFLATS: "SEARCHBUSYFLATS",
  SEARCHFLAT: "SEARCHFLAT",
  SEARCHFLATFORUSER: "SEARCHFLATFORUSER",
  GETFLATINFO: "GETFLATINFO",
  CREATEFLAT: "CREATEFLAT",
  TRYFLAT: "TRYFLAT",
  GOTOFLAT: "GOTOFLAT",
  GETSTRIP: "GETSTRIP",
  GETORDERINFO: "GETORDERINFO",
  PURCHASE: "PURCHASE",
  PLACESTUFFFROMSTRIP: "PLACESTUFFFROMSTRIP",
  PLACEITEMFROMSTRIP: "PLACEITEMFROMSTRIP",
  MOVESTUFF: "MOVESTUFF",
  SETSTUFFDATA: "SETSTUFFDATA",
  ADDSTRIPITEM: "ADDSTRIPITEM",
  REMOVESTUFF: "REMOVESTUFF",
  REMOVEITEM: "REMOVEITEM",
  WAVE: "WAVE",
  Dance: "DANCE",
  Moderator: "MODERATOR",
  STOP: "STOP",
  CHAT: "CHAT",
  SHOUT: "SHOUT",
  WHISPER: "WHISPER"
};

const release1BridgeRegistry: HabboBridgePacketNameRegistry = {
  serverPacketsByHeader: release1ServerPacketsByHeader,
  clientPacketsByHeader: release1ClientPacketsByHeader,
  framing: "v1-text-hash",
  source: "release1 MessengerScript EnterpriseServer Connection Scripts and Roseau NettyResponse hash framing"
};

export function getHabboBridgePacketNameRegistry(adapterId: string): HabboBridgePacketNameRegistry {
  if (adapterId === "release1") {
    return release1BridgeRegistry;
  }

  return adapterId === "release14" ? release14BridgeRegistry : release7BridgeRegistry;
}

export function resolveBridgeServerPacketName(
  registry: HabboBridgePacketNameRegistry,
  header: string,
  headerId: number
): string {
  return registry.serverPacketsByHeader[header]
    ?? registry.serverPacketsByHeaderId?.[headerId]
    ?? "SERVER";
}

export function resolveBridgeClientPacketName(
  registry: HabboBridgePacketNameRegistry,
  header: string,
  headerId: number
): string {
  return registry.clientPacketsByHeader[header]
    ?? registry.clientPacketsByHeaderId?.[headerId]
    ?? "CLIENT";
}
